const MIGRATION_MYSQL_HOST="localhost"
const MIGRATION_MYSQL_USER="root"
const MIGRATION_MYSQL_PASSWORD="bsc59tau"
const MIGRATION_MYSQL_DATABASE="hospital_db"

export {MIGRATION_MYSQL_PASSWORD, MIGRATION_MYSQL_DATABASE, MIGRATION_MYSQL_HOST, MIGRATION_MYSQL_USER}

